/* Magic Mirror Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */
 
var config = {
	address: "localhost", 	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
					// you must set the sub path here. basePath must end with a /
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], 	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],
 
	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true
 
	language: "en",		//"ko"
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device
 
		modules: [
	{
		module: "alert",
	},
	{
		module: "updatenotification",
		position: "top_bar"
	},
	{
		module: "clock",
		position: "top_left"
	},
	{
		module: "calendar",
		header: "나의 일정",
		position: "top_left",
		config: {
		calendars: [
		{
			symbol: "calendar-check",
			url: "https://calendar.google.com/calendar/ical/hjhj3077%40gmail.com/private-3b52f8faaba8b56820e273032228e695/basic.ics"
		}
		]
		}
	},
	 {
		module: "compliments",
		position: "top_center",
		config: {
			compliments: {
				anytime: [
				"Have a nice day : >"
				]
			}
		}
	 },
 
 
	 {
			 module: 'MMM-AirQuality',
			 position: 'top_right',
			 config: {
			  location: 'korea/jeonbuk/geumam-dong',
			  lang: "kr"
			}
		},
	 {
		module: "currentweather",
		position: "top_right",
		header: "현재 날씨",
		config: {
			location: "Jeonju",
			locationID: "1845457", //ID from http://bulk.openweathermap.org/sample... unzip the gz file and find your city
			appid: "5b915641947194e9bdef83e0fd9f7bdf"
		}
	 },
	 {
		module: "weatherforecast",
		position: "top_right",
		header: "날씨 예보",
		config: {
			location: "Jeonju",
			locationID: "1845457", //ID from http://bulk.openweathermap.org/sample... unzip the gz file and find your city
			appid: "5b915641947194e9bdef83e0fd9f7bdf"
		}
	 },
	 {
		module: "newsfeed",
		position: "bottom_bar",
		config: {
			feeds: [
				{
					title: "JTBC",
					url: "http://fs.jtbc.joins.com/RSS/newsflash.xml",
					ref: "http://news.jtbc.joins.com/Etc/RssService.aspx"
				}
			],
			
		showSourceTitle: true,
		showPublishDate: true,
		broadcastNewsFeeds: true,
		broadcastNewsUpdates: true
			}
		},
		{
		module: "MMM-GoogleAssistant",
		position: "fullscreen_above",
		config: {
			assistantConfig: {
				lang: "ko-KR",
				latitude: 37.33,
				longitude: 126.59,
			},
			micConfig: { // put there configuration generated by auto-installer
				recorder: "arecord",
				device: "plughw:1",  // 아까 기록해둔 plughw 번호로 수정
			},
 
			snowboy: {
				audioGain: 2.0,
				Frontend: true,
				Model: "jarvis",
				Sensitivity: null
			},
			NPMCheck: {
				useChecker: false,
				delay: 10 * 60 * 1000,
				useAlert: false
			}	
		}
	},	
		{
		  module: "MMM-GooglePhotos",
		  position: "fullscreen_below",
		  config: {
				albums: ["JBNU micro-processor project"], // 앨범이름을 정확히 써주세요. 예시: ["My wedding", "family share", "Travle to Paris"]
				updateInterval: 10, // 사진 바꿔주는 시간(최소 10초)
				sort: "random", // "old", "random" 보여주는 순서
				uploadAlbum: null, // Only album created by `create_uploadable_album.js`.
				condition: {
					fromDate: null, // Or "2018-03", RFC ... format available
					toDate: null, // Or "2019-12-25",
					minWidth: null, // Or 400
					maxWidth: null, // Or 8000
					minHeight: null, // Or 400
					maxHeight: null, // Or 8000
					minWHRatio: null,
					maxWHRatio: null,
					// WHRatio = Width/Height ratio ( ==1 : Squared Photo,   < 1 : Portraited Photo, > 1 : Landscaped Photo)
				},
				//showWidth: 1080, // These values will be used for quality of downloaded photos to show. real size to show in your MagicMirror region is recommended.
				//showHeight: 1920,
				timeFormat: "YYYY/MM/DD HH:mm", // Or `relative` can be used.
		  }
		},
	]
};
 
 
 
/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
